apiVersion: apps/v1
kind: Deployment
metadata:
  name: bars-depl
spec:
  selector:
    matchLabels:
      app: barservice
  template:
    metadata:
      labels:
        app: barservice
    spec:
      containers:
      - name: barservice
        image: paraylls/barservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name:  bar-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app:  barservice
  ports:
  - name:  barservice
    protocol: TCP
    port:  80
    targetPort:  80