kind: Service
apiVersion: v1
metadata:
  name:  barservice-srv
spec:
  type: NodePort
  selector:
    app: barservice
  ports:
  - name:  barservice
    protocol: TCP
    port:  80
    targetPort:  8080