kind: Service
apiVersion: v1
metadata:
  name:  managernpservice-srv
spec:
  type: NodePort
  selector:
    app: managerservice
  ports:
  - name:  managerservice
    protocol: TCP
    port:  80
    targetPort:  8080